### PR TITLE
Avoid wrong serial number in u-boot env when using the same flash in more than one device.

### PR DESCRIPTION
**Pull request by VittGam**

### CODE REVIEW

**Comment by bkrepo** [comment]
Thank you for your contribution. 
Could you upload the PR again after solving the merge conflict? Some changes are already fixed.

**Comment by VittGam** [comment]
Okay, I'm going to work on this tomorrow.

By the way, I've found a serious problem with the u-boot in Arch Linux, and I think it is related with `saveenv` issue: I see that u-boot corrupts the eMMC at offset 0x2f00000 when saving the environment. Probably because Arch uses single ext4 partition, and not FAT + ext4 partitions, but offset is hardcoded in u-boot.

I'm elaborating the problem so I can submit a proper issue report, either here or to Arch Linux.

EDIT: I still need to elaborate because I'm only 90% sure it's u-boot and not the Linux kernel. But the corruption definitely happens, only with eMMC in eMMC slot. Not with SD, or with eMMC in SD slot with adapter.

**Comment by bkrepo** [comment]
I will look into the issue. Thank you for the report.

**Comment by bkrepo** [comment]
@VittGam 
I don't know clearly about **_saveenv_** issue. I guessed it is that U-boot cannot save environment variable issue, right?

In that case, U-boot can save & load the environment variable actually. But, C2 U-boot reload the environment variable from _boot.ini_ file.

Sequency of operations:
1. C2 U-boot load the environment variable into the U-Boot Environment partition(like common U-boot) . It is saved into the U-Boot Environment partition when we set the environment variable using saveenv, 
2. C2 U-boot load the boot.ini file. And then, C2 U-boot reload the environment variables in boot.ini file.

So, even if we set the U-boot environment variable using saveenv, C2 U-boot cannot use the environment variable if it is in boot.ini file.

**Comment by JeonghwaCho** [comment]
@VittGam 
Thank you for this commit.
It will fix the critical issue and I think it must be applied ASAP.
So, if you're not available to update PR, can we merge it on HK's github?

Thanks.

**Comment by VittGam** [comment]
Hello,

Sorry for the late reply. I have updated the commit.

By the way, I have not had any more time to investigate the eMMC corruption issue at offset 0x2f00000...

Cheers,
Vittorio G

**Pull request merged**
