### PR TITLE
Odroidxu3 v2012.07

### PR DESCRIPTION
**Pull request by wom-bat**
Hi,
  Here are some fixes for u-boot on the XU3.

  --- I've included fanta's fixes from the XU branch to enable HYP mode booting
  --- I've changed the way the fastboot command works, so partitions are checked at flash time, not at fastboot time.  This means you can do
     fastboot boot uImage
  even with an Ubuntu flash layout.

### CODE REVIEW

**Comment by mdrjr** [comment]
89c1cef has no effects here since its targeted only 5410.
Is it needed to get 5422 working too? Can you drop that patch?

**Comment by wom-bat** [comment]
That's true, and I could drop it. Except I think we need to work towards  a single u-boot for all the exynos in the end --- what do you think?

**Comment by mdrjr** [comment]
Maybe on the future.. right now there are other tasks to be filled. 
DId you actually tested that pull request?

**Comment by wom-bat** [comment]
OK, i'll prepare another tree without that patch.

I tested, using the signed bl12 from http://forum.odroid.com/viewtopic.php?f=98&t=6147
I can boot Ubuntu, and use KVM.

This patchset doesn't have the signed prebuilt bl2 in it.  My plan was to try to get it merged, then either someone at Hardkernel could reroll the signed prebuilts, or I could put up another pull request with just that change in it.

**Pull request closed without merging**
